services:
  # Authentication Service
  - type: web
    name: nestjs-auth-service
    env: docker
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerCommand: npm run start:prod:auth
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: nestjs-auth-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nestjs-auth-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: nestjs-auth-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nestjs-auth-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: nestjs-auth-db
          property: database
      - key: AUTH_SERVICE_PORT
        value: 3002
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: LOG_LEVEL
        value: info

  # API Gateway
  - type: web
    name: nestjs-gateway
    env: docker
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerCommand: npm run start:prod:gateway
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GATEWAY_PORT
        value: 10000
      - key: AUTH_SERVICE_HOST
        fromService:
          name: nestjs-auth-service
          type: web
          property: host
      - key: AUTH_SERVICE_PORT
        value: 3002
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: LOG_LEVEL
        value: info
